// Code generated by rr. DO NOT EDIT.

package api

import (
	"github.com/sirkostya009/ggen/decode"
	"github.com/sirkostya009/ggen/encode"
	"github.com/sirkostya009/ggen/scan"
	"net/http"
	"strconv"
	"strings"
	"sync"
)

var readBufPool = sync.Pool{New: func() any { b := make([]byte, 0, 4096); return &b }}

var writeBufPool = sync.Pool{New: func() any { b := make([]byte, 0, 4096); return &b }}

func readJSON[T decode.Decoder[T]](r *http.Request) (T, error) {
	bp := readBufPool.Get().(*[]byte)
	defer readBufPool.Put(bp)
	var s scan.Stream
	s.Reset(r.Body, *bp)
	var zero T
	v, err := zero.DecodeFromStream(&s)
	*bp = s.Bytes()
	return v, err
}

func writeJSONAny(w http.ResponseWriter, v any) error {
	bp := writeBufPool.Get().(*[]byte)
	defer writeBufPool.Put(bp)
	b, err := encode.AppendAny((*bp)[:0], v)
	*bp = b
	if err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	_, _ = w.Write(b)
	return nil
}

func (s *Api) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	path, ok := strings.CutPrefix(r.URL.Path, "/api/")
	if !ok {
		notFound(w)
		return
	}
	switch path {
	case "admin/maintenance":
		r.Pattern = "/api/admin/maintenance"
		if !requireToken(w, r.Header.Get("Authorization")) {
			return
		}
		s.AdminApi.Maintenance(w)
		return
	case "admin/stats":
		if r.Method != "GET" {
			w.Header().Set("Allow", "GET")
			on405(w)
			return
		}
		r.Pattern = "GET /api/admin/stats"
		if !requireToken(w, r.Header.Get("Authorization")) {
			return
		}
		if err := writeJSONAny(w, s.AdminApi.Stats()); err != nil {
			handleError(w, err)
			return
		}
		return
	case "debug/query":
		if r.Method != "GET" {
			w.Header().Set("Allow", "GET")
			on405(w)
			return
		}
		r.Pattern = "GET /api/debug/query"
		v1 := r.URL.Query()
		if err := writeJSONAny(w, s.SearchApi.DebugQuery(v1)); err != nil {
			handleError(w, err)
			return
		}
		return
	case "forms/login":
		if r.Method != "POST" {
			w.Header().Set("Allow", "POST")
			on405(w)
			return
		}
		r.Pattern = "POST /api/forms/login"
		if err := r.ParseForm(); err != nil {
			badRequest(w, r.Header.Get("X-Request-Id"), err)
			return
		}
		if err := writeJSONAny(w, s.FormsApi.Login(r.PostForm)); err != nil {
			handleError(w, err)
			return
		}
		return
	case "forms/upload":
		if r.Method != "POST" {
			w.Header().Set("Allow", "POST")
			on405(w)
			return
		}
		r.Pattern = "POST /api/forms/upload"
		if err := r.ParseMultipartForm(32 << 20); err != nil {
			badRequest(w, r.Header.Get("X-Request-Id"), err)
			return
		}
		if err := writeJSONAny(w, s.FormsApi.Upload(r.MultipartForm)); err != nil {
			handleError(w, err)
			return
		}
		return
	case "meta":
		if r.Method != "GET" {
			w.Header().Set("Allow", "GET")
			on405(w)
			return
		}
		r.Pattern = "GET /api/meta"
		var headers ReqMeta
		headers.RequestID = r.Header.Get("X-Request-Id")
		headers.Trace = r.Header.Get("X-Trace")
		if err := writeJSONAny(w, s.FormsApi.Meta(headers)); err != nil {
			handleError(w, err)
			return
		}
		return
	case "posts":
		switch r.Method {
		case "GET":
			r.Pattern = "GET /api/posts"
			v1 := r.URL.Query()
			var query PostsQuery
			if v2 := v1.Get("page"); v2 != "" {
				var err error
				if query.Page, err = strconv.Atoi(v2); err != nil {
					badRequest(w, r.Header.Get("X-Request-Id"), err)
					return
				}
			}
			query.Tag = v1.Get("tag")
			w.Header().Set("Content-Type", "application/json")
			if err := encode.WriteSliceTo(w, s.PostsApi.ListPosts(query)); err != nil {
				postNotFound(w, r, err)
				return
			}
		case "POST":
			r.Pattern = "POST /api/posts"
			body, err := readJSON[Post](r)
			if err != nil {
				badRequest(w, r.Header.Get("X-Request-Id"), err)
				return
			}
			v1, err := s.PostsApi.CreatePost(&body)
			if err != nil {
				postNotFound(w, r, err)
				return
			}
			w.Header().Set("Content-Type", "application/json")
			if err := encode.WriteTo(w, v1); err != nil {
				postNotFound(w, r, err)
				return
			}
		default:
			w.Header().Set("Allow", "GET, POST")
			on405(w)
		}
		return
	case "search":
		if r.Method != "GET" {
			w.Header().Set("Allow", "GET")
			on405(w)
			return
		}
		r.Pattern = "GET /api/search"
		v1 := r.URL.Query()
		sq, err := parseSearch(v1)
		if err != nil {
			badRequest(w, r.Header.Get("X-Request-Id"), err)
			return
		}
		if err := writeJSONAny(w, s.SearchApi.Search(sq, r.Header.Get("X-Request-Id"))); err != nil {
			handleError(w, err)
			return
		}
		return
	case "users":
		switch r.Method {
		case "GET":
			r.Pattern = "GET /api/users"
			w.Header().Set("Content-Type", "application/json")
			if err := encode.WriteSliceTo(w, s.UsersApi.GetUsers()); err != nil {
				handleError(w, err)
				return
			}
		case "POST":
			r.Pattern = "POST /api/users"
			u, err := readJSON[User](r)
			if err != nil {
				badRequest(w, r.Header.Get("X-Request-Id"), err)
				return
			}
			w.Header().Set("Content-Type", "application/json")
			if err := encode.WriteSliceTo(w, s.UsersApi.PostUser(u)); err != nil {
				handleError(w, err)
				return
			}
		default:
			w.Header().Set("Allow", "GET, POST")
			on405(w)
		}
		return
	}
	if i := strings.IndexByte(path, '/'); i > 0 {
		switch path[:i] {
		case "users":
			p1 := path[i+1:]
			if strings.IndexByte(p1, '/') < 0 {
				if t1, err := strconv.Atoi(p1); err == nil {
					switch r.Method {
					case "GET":
						r.Pattern = "GET /api/users/{i}"
						v1, err := s.UsersApi.GetUser(t1)
						if err != nil {
							handleError(w, err)
							return
						}
						w.Header().Set("Content-Type", "application/json")
						if err := encode.WriteTo(w, v1); err != nil {
							handleError(w, err)
							return
						}
					case "DELETE":
						r.Pattern = "DELETE /api/users/{i}"
						if err := s.UsersApi.DeleteUser(t1); err != nil {
							handleError(w, err)
						}
					default:
						w.Header().Set("Allow", "GET, DELETE")
						on405(w)
					}
					return
				}
			}
		case "posts":
			if r.Method != "GET" {
				w.Header().Set("Allow", "GET")
				on405(w)
				return
			}
			p1 := path[i+1:]
			if i := strings.IndexByte(p1, '/'); i < 0 {
				if t1, err := strconv.Atoi(p1); err == nil {
					r.Pattern = "GET /api/posts/{id}"
					v1, err := s.PostsApi.GetPost(t1)
					if err != nil {
						postNotFound(w, r, err)
						return
					}
					w.Header().Set("Content-Type", "application/json")
					if err := encode.WriteTo(w, v1); err != nil {
						postNotFound(w, r, err)
						return
					}
					return
				}
				if isSlug(p1) {
					r.Pattern = "GET /api/posts/{slug}"
					r.SetPathValue("slug", p1)
					v1, err := s.PostsApi.GetPostBySlug(p1)
					if err != nil {
						postNotFound(w, r, err)
						return
					}
					w.Header().Set("Content-Type", "application/json")
					if err := encode.WriteTo(w, v1); err != nil {
						postNotFound(w, r, err)
						return
					}
					return
				}
			} else if i > 0 {
				s1 := p1[:i]
				if t1, err := strconv.Atoi(s1); err == nil {
					p2 := p1[i+1:]
					if p3, ok := strings.CutPrefix(p2, "comments/"); ok {
						if strings.IndexByte(p3, '/') < 0 {
							if t3, err := strconv.Atoi(p3); err == nil {
								r.Pattern = "GET /api/posts/{pid}/comments/{cid}"
								if err := writeJSONAny(w, s.PostsApi.GetComment(t1, t3)); err != nil {
									postNotFound(w, r, err)
									return
								}
								return
							}
						}
					}
				}
			}
		case "echo":
			if r.Method != "GET" {
				w.Header().Set("Allow", "GET")
				on405(w)
				return
			}
			p1 := path[i+1:]
			if strings.IndexByte(p1, '/') < 0 {
				if t1, err := strconv.ParseFloat(p1, 64); err == nil {
					r.Pattern = "GET /api/echo/{f}"
					if err := writeJSONAny(w, s.SearchApi.EchoFloat(t1)); err != nil {
						handleError(w, err)
						return
					}
					return
				}
				if t1, err := strconv.ParseBool(p1); err == nil {
					r.Pattern = "GET /api/echo/{b}"
					if err := writeJSONAny(w, s.SearchApi.EchoBool(t1)); err != nil {
						handleError(w, err)
						return
					}
					return
				}
				if p1 != "" {
					r.Pattern = "GET /api/echo/{str}"
					r.SetPathValue("str", p1)
					if err := writeJSONAny(w, s.SearchApi.EchoString(p1)); err != nil {
						handleError(w, err)
						return
					}
					return
				}
			}
		case "files":
			if r.Method != "GET" {
				w.Header().Set("Allow", "GET")
				on405(w)
				return
			}
			p1 := path[i+1:]
			r.Pattern = "GET /api/files/{path...}"
			r.SetPathValue("path", p1)
			if err := writeJSONAny(w, s.FilesApi.StatFile(r)); err != nil {
				handleError(w, err)
				return
			}
			return
		}
	}
	notFound(w)
}
