// Code generated by ggen; DO NOT EDIT.

package services

import (
	"math"
	"strconv"
	"strings"
	"unsafe"

	"github.com/sirkostya009/ggen"
)

func (recv Stats) DecodeFrom(data []byte) (result Stats, i int, err error) {
	result = recv
	seenPosts := false
	seenUsers := false
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i >= len(data) || data[i] != '{' {
		return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
	}
	i++
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i < len(data) && data[i] == '}' {
		i++
		if !seenPosts {
			result.Posts = 0
		}
		if !seenUsers {
			result.Users = 0
		}
		return result, i, nil
	}
	for {
		var key string
		if i >= len(data) || data[i] != '"' {
			return result, i, ggen.NewParseErr("", i, ggen.ErrExpectString)
		}
		ke := i + 1
		for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 && data[ke] < 0x80 {
			ke++
		}
		if ke < len(data) && data[ke] == '"' {
			key = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
			i = ke + 1
		} else {
			key, i, err = ggen.String(data, i, true)
			if err != nil {
				return result, i, ggen.NewParseErr("", i, err)
			}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) || data[i] != ':' {
			return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
		}
		i++
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		switch key {
		case "posts":
			if seenPosts {
				return result, i, &ggen.DuplicateKeyError{Pos: i, Path: []string{"posts"}}
			}
			seenPosts = true
			neg := false
			if i < len(data) && data[i] == '-' {
				neg = true
				i++
			}
			if i >= len(data) || data[i] < '0' || data[i] > '9' {
				return result, i, ggen.NewParseErr("posts", i, ggen.ErrBadNumber)
			}
			if data[i] == '0' && i+1 < len(data) && data[i+1] >= '0' && data[i+1] <= '9' {
				return result, i, ggen.NewParseErr("posts", i, ggen.ErrBadNumber)
			}
			limit := uint64(math.MaxInt64)
			if neg {
				limit = ggen.SignedNeg
			}
			var u uint64
			de := i + 18
			if de > len(data) {
				de = len(data)
			}
			for i < de && data[i] >= '0' && data[i] <= '9' {
				u = u*10 + uint64(data[i]-'0')
				i++
			}
			for i < len(data) && data[i] >= '0' && data[i] <= '9' {
				d := uint64(data[i] - '0')
				if u > limit/10 || (u == limit/10 && d > limit%10) {
					return result, i, ggen.NewParseErr("posts", i, ggen.ErrNumberOverflow)
				}
				u = u*10 + d
				i++
			}
			if i < len(data) {
				c := data[i]
				if c == '.' || c == 'e' || c == 'E' {
					return result, i, ggen.NewParseErr("posts", i, ggen.ErrBadNumber)
				}
			}
			var n int64
			if neg {
				if u == ggen.SignedNeg {
					n = math.MinInt64
				} else {
					n = -int64(u)
				}
			} else {
				n = int64(u)
			}
			result.Posts = int(n)
		case "users":
			if seenUsers {
				return result, i, &ggen.DuplicateKeyError{Pos: i, Path: []string{"users"}}
			}
			seenUsers = true
			neg := false
			if i < len(data) && data[i] == '-' {
				neg = true
				i++
			}
			if i >= len(data) || data[i] < '0' || data[i] > '9' {
				return result, i, ggen.NewParseErr("users", i, ggen.ErrBadNumber)
			}
			if data[i] == '0' && i+1 < len(data) && data[i+1] >= '0' && data[i+1] <= '9' {
				return result, i, ggen.NewParseErr("users", i, ggen.ErrBadNumber)
			}
			limit := uint64(math.MaxInt64)
			if neg {
				limit = ggen.SignedNeg
			}
			var u uint64
			de := i + 18
			if de > len(data) {
				de = len(data)
			}
			for i < de && data[i] >= '0' && data[i] <= '9' {
				u = u*10 + uint64(data[i]-'0')
				i++
			}
			for i < len(data) && data[i] >= '0' && data[i] <= '9' {
				d := uint64(data[i] - '0')
				if u > limit/10 || (u == limit/10 && d > limit%10) {
					return result, i, ggen.NewParseErr("users", i, ggen.ErrNumberOverflow)
				}
				u = u*10 + d
				i++
			}
			if i < len(data) {
				c := data[i]
				if c == '.' || c == 'e' || c == 'E' {
					return result, i, ggen.NewParseErr("users", i, ggen.ErrBadNumber)
				}
			}
			var n int64
			if neg {
				if u == ggen.SignedNeg {
					n = math.MinInt64
				} else {
					n = -int64(u)
				}
			} else {
				n = int64(u)
			}
			result.Users = int(n)
		default:
			return result, i, &ggen.UnknownKeyError{Pos: i, Path: []string{key}}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) {
			return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
		}
		if data[i] == ',' {
			i++
			for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			continue
		}
		if data[i] == '}' {
			i++
			if !seenPosts {
				result.Posts = 0
			}
			if !seenUsers {
				result.Users = 0
			}
			return result, i, nil
		}
		return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
	}
}

func (recv Stats) DecodeFromStream(s *ggen.Stream) (result Stats, err error) {
	result = recv
	seenPosts := false
	seenUsers := false
	err = s.ObjectOpen()
	if err != nil {
		return result, ggen.NewParseErr("", s.Offset(), err)
	}
	err = s.SkipSpace()
	if err != nil {
		return result, ggen.NewParseErr("", s.Offset(), err)
	}
	if s.Pos >= len(s.Bytes()) {
		if err = s.ReadMore(s.Pos); err != nil {
			return result, ggen.NewParseErr("", s.Offset(), ggen.NotEOF(err, ggen.ErrExpectString))
		}
		s.Pos = 0
	}
	if s.Bytes()[s.Pos] == '}' {
		s.Pos++
		if !seenPosts {
			result.Posts = 0
		}
		if !seenUsers {
			result.Users = 0
		}
		return result, nil
	}
	for {
		var key string
		key, err = s.KeyView(true)
		if err != nil {
			return result, ggen.NewParseErr("", s.Offset(), err)
		}
		switch key {
		case "posts":
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr("posts", s.Offset(), err)
			}
			if seenPosts {
				return result, &ggen.DuplicateKeyError{Pos: s.Offset(), Path: []string{"posts"}}
			}
			seenPosts = true
			var iv int64
			iv, err = s.Int64()
			if err != nil {
				return result, ggen.NewParseErr("posts", s.Offset(), err)
			}
			result.Posts = int(iv)
		case "users":
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr("users", s.Offset(), err)
			}
			if seenUsers {
				return result, &ggen.DuplicateKeyError{Pos: s.Offset(), Path: []string{"users"}}
			}
			seenUsers = true
			var iv int64
			iv, err = s.Int64()
			if err != nil {
				return result, ggen.NewParseErr("users", s.Offset(), err)
			}
			result.Users = int(iv)
		default:
			ownKey := strings.Clone(key)
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr(ownKey, s.Offset(), err)
			}
			return result, &ggen.UnknownKeyError{Pos: s.Offset(), Path: []string{ownKey}}
		}

		err = s.SkipSpace()
		if err != nil {
			return result, ggen.NewParseErr("", s.Offset(), err)
		}
		if s.Pos >= len(s.Bytes()) {
			if err = s.ReadMore(s.Pos); err != nil {
				return result, ggen.NewParseErr("", s.Offset(), ggen.NotEOF(err, ggen.ErrBadObject))
			}
			s.Pos = 0
		}
		c := s.Bytes()[s.Pos]
		if c == ',' {
			s.Pos++
			err = s.SkipSpace()
			if err != nil {
				return result, ggen.NewParseErr("", s.Offset(), err)
			}
			continue
		}
		if c == '}' {
			s.Pos++
			if !seenPosts {
				result.Posts = 0
			}
			if !seenUsers {
				result.Users = 0
			}
			return result, nil
		}
		return result, ggen.NewParseErr("", s.Offset(), ggen.ErrBadObject)
	}
}

func (s Stats) JSONSize() int {
	size := 59
	return size
}

func (s Stats) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, "{\"posts\":"...)
	dst = strconv.AppendInt(dst, int64(s.Posts), 10)
	dst = append(dst, ",\"users\":"...)
	dst = strconv.AppendInt(dst, int64(s.Users), 10)
	return append(dst, '}'), nil
}

func (recv NewUser) DecodeFrom(data []byte) (result NewUser, i int, err error) {
	result = recv
	seenName := false
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i >= len(data) || data[i] != '{' {
		return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
	}
	i++
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i < len(data) && data[i] == '}' {
		i++
		if !seenName {
			result.Name = ""
		}
		return result, i, nil
	}
	for {
		var key string
		if i >= len(data) || data[i] != '"' {
			return result, i, ggen.NewParseErr("", i, ggen.ErrExpectString)
		}
		ke := i + 1
		for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 && data[ke] < 0x80 {
			ke++
		}
		if ke < len(data) && data[ke] == '"' {
			key = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
			i = ke + 1
		} else {
			key, i, err = ggen.String(data, i, true)
			if err != nil {
				return result, i, ggen.NewParseErr("", i, err)
			}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) || data[i] != ':' {
			return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
		}
		i++
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		switch key {
		case "name":
			if seenName {
				return result, i, &ggen.DuplicateKeyError{Pos: i, Path: []string{"name"}}
			}
			seenName = true
			if i >= len(data) || data[i] != '"' {
				return result, i, ggen.NewParseErr("name", i, ggen.ErrExpectString)
			}
			ke := i + 1
			kew := ke + 32
			if kew > len(data) {
				kew = len(data)
			}
			for ke < kew && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 && data[ke] < 0x80 {
				ke++
			}
			if ke < len(data) && data[ke] == '"' {
				result.Name = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
				i = ke + 1
			} else {
				result.Name, i, err = ggen.String(data, i, true)
				if err != nil {
					return result, i, ggen.NewParseErr("name", i, err)
				}
			}
		default:
			return result, i, &ggen.UnknownKeyError{Pos: i, Path: []string{key}}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) {
			return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
		}
		if data[i] == ',' {
			i++
			for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			continue
		}
		if data[i] == '}' {
			i++
			if !seenName {
				result.Name = ""
			}
			return result, i, nil
		}
		return result, i, ggen.NewParseErr("", i, ggen.ErrBadObject)
	}
}

func (recv NewUser) DecodeFromStream(s *ggen.Stream) (result NewUser, err error) {
	result = recv
	seenName := false
	err = s.ObjectOpen()
	if err != nil {
		return result, ggen.NewParseErr("", s.Offset(), err)
	}
	err = s.SkipSpace()
	if err != nil {
		return result, ggen.NewParseErr("", s.Offset(), err)
	}
	if s.Pos >= len(s.Bytes()) {
		if err = s.ReadMore(s.Pos); err != nil {
			return result, ggen.NewParseErr("", s.Offset(), ggen.NotEOF(err, ggen.ErrExpectString))
		}
		s.Pos = 0
	}
	if s.Bytes()[s.Pos] == '}' {
		s.Pos++
		if !seenName {
			result.Name = ""
		}
		return result, nil
	}
	for {
		var key string
		key, err = s.KeyView(true)
		if err != nil {
			return result, ggen.NewParseErr("", s.Offset(), err)
		}
		switch key {
		case "name":
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr("name", s.Offset(), err)
			}
			if seenName {
				return result, &ggen.DuplicateKeyError{Pos: s.Offset(), Path: []string{"name"}}
			}
			seenName = true
			result.Name, err = s.String(true)
			if err != nil {
				return result, ggen.NewParseErr("name", s.Offset(), err)
			}
		default:
			ownKey := strings.Clone(key)
			err = s.ConsumeColon()
			if err != nil {
				return result, ggen.NewParseErr(ownKey, s.Offset(), err)
			}
			return result, &ggen.UnknownKeyError{Pos: s.Offset(), Path: []string{ownKey}}
		}

		err = s.SkipSpace()
		if err != nil {
			return result, ggen.NewParseErr("", s.Offset(), err)
		}
		if s.Pos >= len(s.Bytes()) {
			if err = s.ReadMore(s.Pos); err != nil {
				return result, ggen.NewParseErr("", s.Offset(), ggen.NotEOF(err, ggen.ErrBadObject))
			}
			s.Pos = 0
		}
		c := s.Bytes()[s.Pos]
		if c == ',' {
			s.Pos++
			err = s.SkipSpace()
			if err != nil {
				return result, ggen.NewParseErr("", s.Offset(), err)
			}
			continue
		}
		if c == '}' {
			s.Pos++
			if !seenName {
				result.Name = ""
			}
			return result, nil
		}
		return result, ggen.NewParseErr("", s.Offset(), ggen.ErrBadObject)
	}
}

func (s NewUser) JSONSize() int {
	size := 11
	size += len(s.Name) * 2
	return size
}

func (s NewUser) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, "{\"name\":\""...)
	dst = ggen.AppendStringNoHTML(dst, s.Name)
	return append(dst, '}'), nil
}
