// Code generated by rr. DO NOT EDIT.

package api

import (
	"net/http"
)

func (s *Api) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	if len(r.URL.Path) >= 5 && r.URL.Path[:5] == "/api/" {
		mp0 := r.URL.Path[5:]
		if len(mp0) > 2 {
			switch mp0[:3] {
			case "v1/":
				s.V1.ServeHTTP(w, r)
				return
			case "v2/":
				s.V2.ServeHTTP(w, r)
				return
			}
		}
	}
	w.WriteHeader(http.StatusNotFound)
}
