// Code generated by rr. DO NOT EDIT.

package api

import (
	"net/http"
	"strings"
)

func (s *Api) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	if strings.HasPrefix(r.URL.Path, "/api/v1/") {
		s.V1.ServeHTTP(w, r)
		return
	}
	if strings.HasPrefix(r.URL.Path, "/api/v2/") {
		s.V2.ServeHTTP(w, r)
		return
	}
	w.WriteHeader(http.StatusNotFound)
}
