// Code generated by rr. DO NOT EDIT.

package v2

import (
	"github.com/sirkostya009/ggen"
	"net/http"
	"strconv"
	"strings"
	"sync"
	"versioned/services"
)

var __jsonCT = []string{"application/json"}

var readBufPool = sync.Pool{New: func() any { b := make([]byte, 0, 4096); return &b }}

var writeBufPool = sync.Pool{New: func() any { b := make([]byte, 0, 4096); return &b }}

func readJSON[T ggen.StreamDecoder[T]](r *http.Request) (T, error) {
	bp := readBufPool.Get().(*[]byte)
	defer readBufPool.Put(bp)
	var s ggen.Stream
	s.Reset(r.Body, *bp)
	var zero T
	v, err := zero.DecodeFromStream(&s)
	*bp = s.Bytes()
	return v, err
}

func readJSONSlice[T ggen.StreamDecoder[T]](r *http.Request) ([]T, error) {
	bp := readBufPool.Get().(*[]byte)
	defer readBufPool.Put(bp)
	var s ggen.Stream
	vs, err := s.Reset(r.Body, *bp).Slice[T]()
	*bp = s.Bytes()
	return vs, err
}

func writeJSONAny(w http.ResponseWriter, v any) error {
	bp := writeBufPool.Get().(*[]byte)
	defer writeBufPool.Put(bp)
	b, err := ggen.AppendAny((*bp)[:0], v)
	*bp = b
	if err != nil {
		return err
	}
	w.Header()["Content-Type"] = __jsonCT
	_, _ = w.Write(b)
	return nil
}

func (s *Api) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	var err error
	var post Post
	var newUser services.NewUser
	var newUsers []services.NewUser
	var user User
	path := r.URL.Path
	if len(path) < 8 || path[:8] != "/api/v2/" {
		notFound(w)
		return
	}
	path = path[8:]
	switch path {
	case "admin/maintenance":
		r.Pattern = "/api/v2/admin/maintenance"
		if !requireToken(r.Context(), w, r.Header.Get("Authorization")) {
			return
		}
		s.AdminApi.Maintenance(w)
		return
	case "admin/stats":
		if r.Method != "GET" {
			w.Header().Set("Allow", "GET")
			on405(w)
			return
		}
		r.Pattern = "GET /api/v2/admin/stats"
		if !requireToken(r.Context(), w, r.Header.Get("Authorization")) {
			return
		}
		w.Header()["Content-Type"] = __jsonCT
		if err := ggen.WriteTo(w, s.AdminApi.Stats()); err != nil {
			handleError(w, err)
			return
		}
		return
	case "posts":
		switch r.Method {
		case "GET":
			r.Pattern = "GET /api/v2/posts"
			v1 := r.URL.Query()
			var query PostsQuery
			if v2 := v1.Get("page"); v2 != "" {
				var err error
				if query.Page, err = strconv.Atoi(v2); err != nil {
					badRequest(w, err)
					return
				}
			}
			query.Tag = v1.Get("tag")
			w.Header()["Content-Type"] = __jsonCT
			if err := ggen.WriteSliceTo(w, s.PostsApi.ListPosts(query)); err != nil {
				postNotFound(w, r, err)
				return
			}
		case "POST":
			r.Pattern = "POST /api/v2/posts"
			post, err = readJSON[Post](r)
			if err != nil {
				badRequest(w, err)
				return
			}
			post, err = s.PostsApi.CreatePost(&post)
			if err != nil {
				postNotFound(w, r, err)
				return
			}
			w.Header()["Content-Type"] = __jsonCT
			if err := ggen.WriteTo(w, post); err != nil {
				postNotFound(w, r, err)
				return
			}
		default:
			w.Header().Set("Allow", "GET, POST")
			on405(w)
		}
		return
	case "users":
		switch r.Method {
		case "GET":
			r.Pattern = "GET /api/v2/users"
			w.Header()["Content-Type"] = __jsonCT
			if err := ggen.WriteSliceTo(w, s.UsersApi.GetUsers()); err != nil {
				handleError(w, err)
				return
			}
		case "POST":
			r.Pattern = "POST /api/v2/users"
			newUser, err = readJSON[services.NewUser](r)
			if err != nil {
				badRequest(w, err)
				return
			}
			w.Header()["Content-Type"] = __jsonCT
			if err := ggen.WriteTo(w, s.UsersApi.PostUser(newUser)); err != nil {
				handleError(w, err)
				return
			}
		default:
			w.Header().Set("Allow", "GET, POST")
			on405(w)
		}
		return
	case "users/bulk":
		if r.Method != "POST" {
			w.Header().Set("Allow", "POST")
			on405(w)
			return
		}
		r.Pattern = "POST /api/v2/users/bulk"
		newUsers, err = readJSONSlice[services.NewUser](r)
		if err != nil {
			badRequest(w, err)
			return
		}
		w.Header()["Content-Type"] = __jsonCT
		if err := ggen.WriteSliceTo(w, s.UsersApi.PostUsers(newUsers)); err != nil {
			handleError(w, err)
			return
		}
		return
	case "users/me":
		if r.Method != "GET" {
			w.Header().Set("Allow", "GET")
			on405(w)
			return
		}
		r.Pattern = "GET /api/v2/users/me"
		user, err = s.UsersApi.GetMe(r.Header.Get("X-User-Id"))
		if err != nil {
			handleError(w, err)
			return
		}
		w.Header()["Content-Type"] = __jsonCT
		if err := ggen.WriteTo(w, user); err != nil {
			handleError(w, err)
			return
		}
		return
	}
	if len(path) > 5 && path[5] == '/' {
		switch path[:5] {
		case "users":
			path = path[6:]
			if strings.IndexByte(path, '/') < 0 {
				if path != "" {
					switch r.Method {
					case "GET":
						r.Pattern = "GET /api/v2/users/{id}"
						r.SetPathValue("id", path)
						user, err = s.UsersApi.GetUser(path)
						if err != nil {
							handleError(w, err)
							return
						}
						w.Header()["Content-Type"] = __jsonCT
						if err := ggen.WriteTo(w, user); err != nil {
							handleError(w, err)
							return
						}
					case "DELETE":
						r.Pattern = "DELETE /api/v2/users/{id}"
						r.SetPathValue("id", path)
						if err := s.UsersApi.DeleteUser(path); err != nil {
							handleError(w, err)
						}
					default:
						w.Header().Set("Allow", "GET, DELETE")
						on405(w)
					}
					return
				}
			}
		case "posts":
			if r.Method != "GET" {
				w.Header().Set("Allow", "GET")
				on405(w)
				return
			}
			path = path[6:]
			if i := strings.IndexByte(path, '/'); i < 0 {
				if isUUID(path) {
					r.Pattern = "GET /api/v2/posts/{id}"
					r.SetPathValue("id", path)
					post, err = s.PostsApi.GetPost(path)
					if err != nil {
						postNotFound(w, r, err)
						return
					}
					w.Header()["Content-Type"] = __jsonCT
					if err := ggen.WriteTo(w, post); err != nil {
						postNotFound(w, r, err)
						return
					}
					return
				}
				if isSlug(path) {
					r.Pattern = "GET /api/v2/posts/{slug}"
					r.SetPathValue("slug", path)
					post, err = s.PostsApi.GetPostBySlug(path)
					if err != nil {
						postNotFound(w, r, err)
						return
					}
					w.Header()["Content-Type"] = __jsonCT
					if err := ggen.WriteTo(w, post); err != nil {
						postNotFound(w, r, err)
						return
					}
					return
				}
			} else if i > 0 {
				s1 := path[:i]
				if isUUID(s1) {
					path = path[i+1:]
					if len(path) >= 9 && path[:9] == "comments/" {
						path = path[9:]
						if strings.IndexByte(path, '/') < 0 {
							if isUUID(path) {
								r.Pattern = "GET /api/v2/posts/{pid}/comments/{cid}"
								r.SetPathValue("pid", s1)
								r.SetPathValue("cid", path)
								if err := writeJSONAny(w, s.PostsApi.GetComment(s1, path)); err != nil {
									postNotFound(w, r, err)
									return
								}
								return
							}
						}
					}
				}
			}
		}
	}
	notFound(w)
}
