// Code generated by rr. DO NOT EDIT.

package v2

import (
	"github.com/sirkostya009/ggen/decode"
	"github.com/sirkostya009/ggen/encode"
	"github.com/sirkostya009/ggen/scan"
	"net/http"
	"strconv"
	"strings"
	"sync"
)

var readBufPool = sync.Pool{New: func() any { b := make([]byte, 0, 4096); return &b }}

var writeBufPool = sync.Pool{New: func() any { b := make([]byte, 0, 4096); return &b }}

func readJSON[T decode.Decoder[T]](r *http.Request) (T, error) {
	bp := readBufPool.Get().(*[]byte)
	defer readBufPool.Put(bp)
	var s scan.Stream
	s.Reset(r.Body, *bp)
	var zero T
	v, err := zero.DecodeFromStream(&s)
	*bp = s.Bytes()
	return v, err
}

func writeJSONAny(w http.ResponseWriter, v any) error {
	bp := writeBufPool.Get().(*[]byte)
	defer writeBufPool.Put(bp)
	b, err := encode.AppendAny((*bp)[:0], v)
	*bp = b
	if err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	_, _ = w.Write(b)
	return nil
}

func (s *Api) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	path, ok := strings.CutPrefix(r.URL.Path, "/api/v2/")
	if !ok {
		notFound(w)
		return
	}
	switch path {
	case "admin/maintenance":
		r.Pattern = "/api/v2/admin/maintenance"
		if !requireToken(w, r.Header.Get("Authorization")) {
			return
		}
		s.AdminApi.Maintenance(w)
		return
	case "admin/stats":
		if r.Method != "GET" {
			w.Header().Set("Allow", "GET")
			on405(w)
			return
		}
		r.Pattern = "GET /api/v2/admin/stats"
		if !requireToken(w, r.Header.Get("Authorization")) {
			return
		}
		if err := writeJSONAny(w, s.AdminApi.Stats()); err != nil {
			handleError(w, err)
			return
		}
		return
	case "posts":
		switch r.Method {
		case "GET":
			r.Pattern = "GET /api/v2/posts"
			v1 := r.URL.Query()
			var query PostsQuery
			if v2 := v1.Get("page"); v2 != "" {
				var err error
				if query.Page, err = strconv.Atoi(v2); err != nil {
					badRequest(w, err)
					return
				}
			}
			query.Tag = v1.Get("tag")
			w.Header().Set("Content-Type", "application/json")
			if err := encode.WriteSliceTo(w, s.PostsApi.ListPosts(query)); err != nil {
				postNotFound(w, r, err)
				return
			}
		case "POST":
			r.Pattern = "POST /api/v2/posts"
			body, err := readJSON[Post](r)
			if err != nil {
				badRequest(w, err)
				return
			}
			v1, err := s.PostsApi.CreatePost(&body)
			if err != nil {
				postNotFound(w, r, err)
				return
			}
			w.Header().Set("Content-Type", "application/json")
			if err := encode.WriteTo(w, v1); err != nil {
				postNotFound(w, r, err)
				return
			}
		default:
			w.Header().Set("Allow", "GET, POST")
			on405(w)
		}
		return
	case "users":
		switch r.Method {
		case "GET":
			r.Pattern = "GET /api/v2/users"
			w.Header().Set("Content-Type", "application/json")
			if err := encode.WriteSliceTo(w, s.UsersApi.GetUsers()); err != nil {
				handleError(w, err)
				return
			}
		case "POST":
			r.Pattern = "POST /api/v2/users"
			body, err := readJSON[User](r)
			if err != nil {
				badRequest(w, err)
				return
			}
			w.Header().Set("Content-Type", "application/json")
			if err := encode.WriteTo(w, s.UsersApi.PostUser(body)); err != nil {
				handleError(w, err)
				return
			}
		default:
			w.Header().Set("Allow", "GET, POST")
			on405(w)
		}
		return
	}
	if i := strings.IndexByte(path, '/'); i > 0 {
		switch path[:i] {
		case "users":
			p1 := path[i+1:]
			if strings.IndexByte(p1, '/') < 0 {
				if p1 != "" {
					switch r.Method {
					case "GET":
						r.Pattern = "GET /api/v2/users/{id}"
						r.SetPathValue("id", p1)
						v1, err := s.UsersApi.GetUser(p1)
						if err != nil {
							handleError(w, err)
							return
						}
						w.Header().Set("Content-Type", "application/json")
						if err := encode.WriteTo(w, v1); err != nil {
							handleError(w, err)
							return
						}
					case "DELETE":
						r.Pattern = "DELETE /api/v2/users/{id}"
						r.SetPathValue("id", p1)
						if err := s.UsersApi.DeleteUser(p1); err != nil {
							handleError(w, err)
						}
					default:
						w.Header().Set("Allow", "GET, DELETE")
						on405(w)
					}
					return
				}
			}
		case "posts":
			if r.Method != "GET" {
				w.Header().Set("Allow", "GET")
				on405(w)
				return
			}
			p1 := path[i+1:]
			if i := strings.IndexByte(p1, '/'); i < 0 {
				if isUUID(p1) {
					r.Pattern = "GET /api/v2/posts/{id}"
					r.SetPathValue("id", p1)
					v1, err := s.PostsApi.GetPost(p1)
					if err != nil {
						postNotFound(w, r, err)
						return
					}
					w.Header().Set("Content-Type", "application/json")
					if err := encode.WriteTo(w, v1); err != nil {
						postNotFound(w, r, err)
						return
					}
					return
				}
				if isSlug(p1) {
					r.Pattern = "GET /api/v2/posts/{slug}"
					r.SetPathValue("slug", p1)
					v1, err := s.PostsApi.GetPostBySlug(p1)
					if err != nil {
						postNotFound(w, r, err)
						return
					}
					w.Header().Set("Content-Type", "application/json")
					if err := encode.WriteTo(w, v1); err != nil {
						postNotFound(w, r, err)
						return
					}
					return
				}
			} else if i > 0 {
				s1 := p1[:i]
				if isUUID(s1) {
					p2 := p1[i+1:]
					if p3, ok := strings.CutPrefix(p2, "comments/"); ok {
						if strings.IndexByte(p3, '/') < 0 {
							if isUUID(p3) {
								r.Pattern = "GET /api/v2/posts/{pid}/comments/{cid}"
								r.SetPathValue("pid", s1)
								r.SetPathValue("cid", p3)
								if err := writeJSONAny(w, s.PostsApi.GetComment(s1, p3)); err != nil {
									postNotFound(w, r, err)
									return
								}
								return
							}
						}
					}
				}
			}
		}
	}
	notFound(w)
}
