// Code generated by rr. DO NOT EDIT.

package v1

import (
	"github.com/sirkostya009/ggen"
	"net/http"
	"strconv"
	"strings"
	"sync"
)

var __jsonCT = []string{"application/json"}

var readBufPool = sync.Pool{New: func() any { b := make([]byte, 0, 4096); return &b }}

var writeBufPool = sync.Pool{New: func() any { b := make([]byte, 0, 4096); return &b }}

func readJSON[T ggen.StreamDecoder[T]](r *http.Request) (T, error) {
	bp := readBufPool.Get().(*[]byte)
	defer readBufPool.Put(bp)
	var s ggen.Stream
	s.Reset(r.Body, *bp)
	var zero T
	v, err := zero.DecodeFromStream(&s)
	*bp = s.Bytes()
	return v, err
}

func writeJSONAny(w http.ResponseWriter, v any) error {
	bp := writeBufPool.Get().(*[]byte)
	defer writeBufPool.Put(bp)
	b, err := ggen.AppendAny((*bp)[:0], v)
	*bp = b
	if err != nil {
		return err
	}
	w.Header()["Content-Type"] = __jsonCT
	_, _ = w.Write(b)
	return nil
}

func (s *Api) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	var err error
	var post Post
	var users []User
	var user User
	var intVal int
	var intVal1 int
	var float64Val float64
	var boolVal bool
	path := r.URL.Path
	if len(path) < 8 || path[:8] != "/api/v1/" {
		notFound(w)
		return
	}
	path = path[8:]
	switch path {
	case "admin/maintenance":
		r.Pattern = "/api/v1/admin/maintenance"
		if !requireToken(w, r.Header.Get("Authorization")) {
			return
		}
		s.AdminApi.Maintenance(w)
		return
	case "admin/stats":
		if r.Method != "GET" {
			w.Header().Set("Allow", "GET")
			on405(w)
			return
		}
		r.Pattern = "GET /api/v1/admin/stats"
		if !requireToken(w, r.Header.Get("Authorization")) {
			return
		}
		if err := writeJSONAny(w, s.AdminApi.Stats()); err != nil {
			handleError(w, err)
			return
		}
		return
	case "debug/query":
		if r.Method != "GET" {
			w.Header().Set("Allow", "GET")
			on405(w)
			return
		}
		r.Pattern = "GET /api/v1/debug/query"
		v1 := r.URL.Query()
		if err := writeJSONAny(w, s.SearchApi.DebugQuery(v1)); err != nil {
			handleError(w, err)
			return
		}
		return
	case "forms/login":
		if r.Method != "POST" {
			w.Header().Set("Allow", "POST")
			on405(w)
			return
		}
		r.Pattern = "POST /api/v1/forms/login"
		if err := r.ParseForm(); err != nil {
			badRequest(w, r.Header.Get("X-Request-Id"), err)
			return
		}
		if err := writeJSONAny(w, s.FormsApi.Login(r.PostForm)); err != nil {
			handleError(w, err)
			return
		}
		return
	case "forms/upload":
		if r.Method != "POST" {
			w.Header().Set("Allow", "POST")
			on405(w)
			return
		}
		r.Pattern = "POST /api/v1/forms/upload"
		if err := r.ParseMultipartForm(32 << 20); err != nil {
			badRequest(w, r.Header.Get("X-Request-Id"), err)
			return
		}
		if err := writeJSONAny(w, s.FormsApi.Upload(r.MultipartForm)); err != nil {
			handleError(w, err)
			return
		}
		return
	case "meta":
		if r.Method != "GET" {
			w.Header().Set("Allow", "GET")
			on405(w)
			return
		}
		r.Pattern = "GET /api/v1/meta"
		var headers ReqMeta
		headers.RequestID = r.Header.Get("X-Request-Id")
		headers.Trace = r.Header.Get("X-Trace")
		if err := writeJSONAny(w, s.FormsApi.Meta(headers)); err != nil {
			handleError(w, err)
			return
		}
		return
	case "posts":
		switch r.Method {
		case "GET":
			r.Pattern = "GET /api/v1/posts"
			v1 := r.URL.Query()
			var query PostsQuery
			if v2 := v1.Get("page"); v2 != "" {
				var err error
				if query.Page, err = strconv.Atoi(v2); err != nil {
					badRequest(w, r.Header.Get("X-Request-Id"), err)
					return
				}
			}
			query.Tag = v1.Get("tag")
			w.Header()["Content-Type"] = __jsonCT
			if err := ggen.WriteSliceTo(w, s.PostsApi.ListPosts(query)); err != nil {
				postNotFound(w, r, err)
				return
			}
		case "POST":
			r.Pattern = "POST /api/v1/posts"
			post, err = readJSON[Post](r)
			if err != nil {
				badRequest(w, r.Header.Get("X-Request-Id"), err)
				return
			}
			post, err = s.PostsApi.CreatePost(&post)
			if err != nil {
				postNotFound(w, r, err)
				return
			}
			w.Header()["Content-Type"] = __jsonCT
			if err := ggen.WriteTo(w, post); err != nil {
				postNotFound(w, r, err)
				return
			}
		default:
			w.Header().Set("Allow", "GET, POST")
			on405(w)
		}
		return
	case "search":
		if r.Method != "GET" {
			w.Header().Set("Allow", "GET")
			on405(w)
			return
		}
		r.Pattern = "GET /api/v1/search"
		v1 := r.URL.Query()
		sq, err := parseSearch(v1)
		if err != nil {
			badRequest(w, r.Header.Get("X-Request-Id"), err)
			return
		}
		if err := writeJSONAny(w, s.SearchApi.Search(sq, r.Header.Get("X-Request-Id"))); err != nil {
			handleError(w, err)
			return
		}
		return
	case "users":
		switch r.Method {
		case "GET":
			r.Pattern = "GET /api/v1/users"
			users, err = s.UsersApi.GetUsers(r.Context())
			if err != nil {
				handleError(w, err)
				return
			}
			w.Header()["Content-Type"] = __jsonCT
			if err := ggen.WriteSliceTo(w, users); err != nil {
				handleError(w, err)
				return
			}
		case "POST":
			r.Pattern = "POST /api/v1/users"
			user, err = readJSON[User](r)
			if err != nil {
				badRequest(w, r.Header.Get("X-Request-Id"), err)
				return
			}
			w.Header()["Content-Type"] = __jsonCT
			if err := ggen.WriteSliceTo(w, s.UsersApi.PostUser(user)); err != nil {
				handleError(w, err)
				return
			}
		default:
			w.Header().Set("Allow", "GET, POST")
			on405(w)
		}
		return
	case "users/me":
		if r.Method != "GET" {
			w.Header().Set("Allow", "GET")
			on405(w)
			return
		}
		r.Pattern = "GET /api/v1/users/me"
		var v1 int
		if v2 := r.Header.Get("X-User-Index"); v2 != "" {
			var err error
			if v1, err = atoi(v2); err != nil {
				badRequest(w, r.Header.Get("X-Request-Id"), err)
				return
			}
		}
		user, err = s.UsersApi.GetMe(v1)
		if err != nil {
			handleError(w, err)
			return
		}
		w.Header()["Content-Type"] = __jsonCT
		if err := ggen.WriteTo(w, user); err != nil {
			handleError(w, err)
			return
		}
		return
	}
	if i := strings.IndexByte(path, '/'); i > 0 {
		switch path[:i] {
		case "users":
			path = path[i+1:]
			if strings.IndexByte(path, '/') < 0 {
				if intVal, err = strconv.Atoi(path); err == nil {
					switch r.Method {
					case "GET":
						r.Pattern = "GET /api/v1/users/{i}"
						user, err = s.UsersApi.GetUser(intVal)
						if err != nil {
							handleError(w, err)
							return
						}
						w.Header()["Content-Type"] = __jsonCT
						if err := ggen.WriteTo(w, user); err != nil {
							handleError(w, err)
							return
						}
					case "DELETE":
						r.Pattern = "DELETE /api/v1/users/{i}"
						if err := s.UsersApi.DeleteUser(intVal); err != nil {
							handleError(w, err)
						}
					default:
						w.Header().Set("Allow", "GET, DELETE")
						on405(w)
					}
					return
				}
				if isUUID(path) {
					if r.Method != "GET" {
						w.Header().Set("Allow", "GET")
						on405(w)
						return
					}
					r.Pattern = "GET /api/v1/users/{id}"
					r.SetPathValue("id", path)
					user, err = s.UsersApi.GetUserByID(path)
					if err != nil {
						handleError(w, err)
						return
					}
					w.Header()["Content-Type"] = __jsonCT
					if err := ggen.WriteTo(w, user); err != nil {
						handleError(w, err)
						return
					}
					return
				}
			}
		case "posts":
			if r.Method != "GET" {
				w.Header().Set("Allow", "GET")
				on405(w)
				return
			}
			path = path[i+1:]
			if i := strings.IndexByte(path, '/'); i < 0 {
				if intVal, err = strconv.Atoi(path); err == nil {
					r.Pattern = "GET /api/v1/posts/{id}"
					post, err = s.PostsApi.GetPost(intVal)
					if err != nil {
						postNotFound(w, r, err)
						return
					}
					w.Header()["Content-Type"] = __jsonCT
					if err := ggen.WriteTo(w, post); err != nil {
						postNotFound(w, r, err)
						return
					}
					return
				}
				if isSlug(path) {
					r.Pattern = "GET /api/v1/posts/{slug}"
					r.SetPathValue("slug", path)
					post, err = s.PostsApi.GetPostBySlug(path)
					if err != nil {
						postNotFound(w, r, err)
						return
					}
					w.Header()["Content-Type"] = __jsonCT
					if err := ggen.WriteTo(w, post); err != nil {
						postNotFound(w, r, err)
						return
					}
					return
				}
			} else if i > 0 {
				s1 := path[:i]
				if intVal, err = strconv.Atoi(s1); err == nil {
					path = path[i+1:]
					if len(path) >= 9 && path[:9] == "comments/" {
						path = path[9:]
						if strings.IndexByte(path, '/') < 0 {
							if intVal1, err = strconv.Atoi(path); err == nil {
								r.Pattern = "GET /api/v1/posts/{pid}/comments/{cid}"
								if err := writeJSONAny(w, s.PostsApi.GetComment(intVal, intVal1)); err != nil {
									postNotFound(w, r, err)
									return
								}
								return
							}
						}
					}
				}
			}
		case "echo":
			if r.Method != "GET" {
				w.Header().Set("Allow", "GET")
				on405(w)
				return
			}
			path = path[i+1:]
			if strings.IndexByte(path, '/') < 0 {
				if float64Val, err = strconv.ParseFloat(path, 64); err == nil {
					r.Pattern = "GET /api/v1/echo/{f}"
					if err := writeJSONAny(w, s.SearchApi.EchoFloat(float64Val)); err != nil {
						handleError(w, err)
						return
					}
					return
				}
				if boolVal, err = strconv.ParseBool(path); err == nil {
					r.Pattern = "GET /api/v1/echo/{b}"
					if err := writeJSONAny(w, s.SearchApi.EchoBool(boolVal)); err != nil {
						handleError(w, err)
						return
					}
					return
				}
				if path != "" {
					r.Pattern = "GET /api/v1/echo/{str}"
					r.SetPathValue("str", path)
					if err := writeJSONAny(w, s.SearchApi.EchoString(path)); err != nil {
						handleError(w, err)
						return
					}
					return
				}
			}
		case "files":
			if r.Method != "GET" {
				w.Header().Set("Allow", "GET")
				on405(w)
				return
			}
			path = path[i+1:]
			r.Pattern = "GET /api/v1/files/{path...}"
			r.SetPathValue("path", path)
			if err := writeJSONAny(w, s.FilesApi.StatFile(r)); err != nil {
				handleError(w, err)
				return
			}
			return
		}
	}
	notFound(w)
}
