// Code generated by ggen; DO NOT EDIT.

package v1

import (
	"math"
	"strconv"
	"strings"
	"unsafe"

	"github.com/sirkostya009/ggen/decode"
	"github.com/sirkostya009/ggen/encode"
	"github.com/sirkostya009/ggen/scan"
	"github.com/sirkostya009/ggen/validation"
)

func (recv Post) DecodeFrom(data []byte) (result Post, i int, err error) {
	result = recv
	if result.Tags != nil {
		result.Tags = result.Tags[:0]
	}
	seenID := false
	seenSlug := false
	seenTags := false
	seenTitle := false
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i >= len(data) || data[i] != '{' {
		return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
	}
	i++
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i < len(data) && data[i] == '}' {
		i++
		return result, i, nil
	}
	for {
		var key string
		if i >= len(data) || data[i] != '"' {
			return result, i, decode.NewParseErr("", i, scan.ErrExpectString)
		}
		ke := i + 1
		for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 && data[ke] < 0x80 {
			ke++
		}
		if ke >= len(data) {
			return result, i, decode.NewParseErr("", i, scan.ErrUnterminated)
		}
		if data[ke] < 0x20 {
			return result, i, decode.NewParseErr("", i, scan.ErrBadString)
		}
		if data[ke] == '"' {
			key = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
			i = ke + 1
		} else {
			key, i, err = scan.String(data, i, true)
			if err != nil {
				return result, i, decode.NewParseErr("", i, err)
			}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) || data[i] != ':' {
			return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
		}
		i++
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		switch key {
		case "id":
			if seenID {
				return result, i, &validation.DuplicateKeyError{Pos: i, Path: []string{"id"}}
			}
			seenID = true
			neg := false
			if i < len(data) && data[i] == '-' {
				neg = true
				i++
			}
			if i >= len(data) || data[i] < '0' || data[i] > '9' {
				return result, i, decode.NewParseErr("id", i, scan.ErrBadNumber)
			}
			if data[i] == '0' && i+1 < len(data) && data[i+1] >= '0' && data[i+1] <= '9' {
				return result, i, decode.NewParseErr("id", i, scan.ErrBadNumber)
			}
			limit := uint64(math.MaxInt64)
			if neg {
				limit = scan.SignedNeg
			}
			var u uint64
			de := i + 18
			if de > len(data) {
				de = len(data)
			}
			for i < de && data[i] >= '0' && data[i] <= '9' {
				u = u*10 + uint64(data[i]-'0')
				i++
			}
			for i < len(data) && data[i] >= '0' && data[i] <= '9' {
				d := uint64(data[i] - '0')
				if u > limit/10 || (u == limit/10 && d > limit%10) {
					return result, i, decode.NewParseErr("id", i, scan.ErrNumberOverflow)
				}
				u = u*10 + d
				i++
			}
			if i < len(data) {
				c := data[i]
				if c == '.' || c == 'e' || c == 'E' {
					return result, i, decode.NewParseErr("id", i, scan.ErrBadNumber)
				}
			}
			var n int64
			if neg {
				if u == scan.SignedNeg {
					n = math.MinInt64
				} else {
					n = -int64(u)
				}
			} else {
				n = int64(u)
			}
			result.ID = int(n)
		case "slug":
			if seenSlug {
				return result, i, &validation.DuplicateKeyError{Pos: i, Path: []string{"slug"}}
			}
			seenSlug = true
			if i >= len(data) || data[i] != '"' {
				return result, i, decode.NewParseErr("slug", i, scan.ErrExpectString)
			}
			ke := i + 1
			kew := ke + 32
			if kew > len(data) {
				kew = len(data)
			}
			for ke < kew && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 && data[ke] < 0x80 {
				ke++
			}
			if ke < len(data) && data[ke] == '"' {
				result.Slug = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
				i = ke + 1
			} else {
				result.Slug, i, err = scan.String(data, i, true)
				if err != nil {
					return result, i, decode.NewParseErr("slug", i, err)
				}
			}
			if !isSlug(result.Slug) {
				return result, i, &validation.PredicateError{Pos: i, Path: []string{"slug"}, Name: "isSlug", Msg: "", Value: result.Slug}
			}
		case "tags":
			if seenTags {
				return result, i, &validation.DuplicateKeyError{Pos: i, Path: []string{"tags"}}
			}
			seenTags = true
			if i+4 <= len(data) && data[i] == 'n' && data[i+1] == 'u' && data[i+2] == 'l' && data[i+3] == 'l' {
				i += 4
				result.Tags = nil
				break
			}
			if i >= len(data) || data[i] != '[' {
				return result, i, scan.ErrBadArray
			}
			i++
			for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			if i < len(data) && data[i] == ']' {
				if result.Tags == nil {
					result.Tags = []string{}
				}
			} else {
				if result.Tags == nil {
					result.Tags = make([]string, 0, 4)
				}
			}
			if i < len(data) && data[i] != ']' {
				for {
					result.Tags = append(result.Tags, "")
					if i >= len(data) || data[i] != '"' {
						return result, i, decode.NewParseErr("tags", i, scan.ErrExpectString)
					}
					ke := i + 1
					kew := ke + 32
					if kew > len(data) {
						kew = len(data)
					}
					for ke < kew && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 && data[ke] < 0x80 {
						ke++
					}
					if ke < len(data) && data[ke] == '"' {
						result.Tags[len(result.Tags)-1] = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
						i = ke + 1
					} else {
						result.Tags[len(result.Tags)-1], i, err = scan.String(data, i, true)
						if err != nil {
							return result, i, decode.NewParseErr("tags", i, err)
						}
					}
					for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
						i++
					}
					if i < len(data) && data[i] == ',' {
						i++
						for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
							i++
						}
						if i >= len(data) || data[i] == ']' {
							return result, i, scan.ErrBadArray
						}
						continue
					}
					break
				}
			}
			if i >= len(data) || data[i] != ']' {
				return result, i, scan.ErrBadArray
			}
			i++
		case "title":
			if seenTitle {
				return result, i, &validation.DuplicateKeyError{Pos: i, Path: []string{"title"}}
			}
			seenTitle = true
			if i >= len(data) || data[i] != '"' {
				return result, i, decode.NewParseErr("title", i, scan.ErrExpectString)
			}
			ke := i + 1
			kew := ke + 32
			if kew > len(data) {
				kew = len(data)
			}
			for ke < kew && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 && data[ke] < 0x80 {
				ke++
			}
			if ke < len(data) && data[ke] == '"' {
				result.Title = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
				i = ke + 1
			} else {
				result.Title, i, err = scan.String(data, i, true)
				if err != nil {
					return result, i, decode.NewParseErr("title", i, err)
				}
			}
		default:
			return result, i, &validation.UnknownKeyError{Pos: i, Path: []string{key}}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) {
			return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
		}
		if data[i] == ',' {
			i++
			for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			continue
		}
		if data[i] == '}' {
			i++
			return result, i, nil
		}
		return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
	}
}

func (recv Post) DecodeFromStream(s *scan.Stream) (result Post, err error) {
	result = recv
	if result.Tags != nil {
		result.Tags = result.Tags[:0]
	}
	seenID := false
	seenSlug := false
	seenTags := false
	seenTitle := false
	err = s.ObjectOpen()
	if err != nil {
		return result, decode.NewParseErr("", s.Pos, err)
	}
	err = s.SkipSpace()
	if err != nil {
		return result, decode.NewParseErr("", s.Pos, err)
	}
	if s.Pos >= len(s.Bytes()) {
		if err = s.ReadMore(s.Pos); err != nil {
			return result, decode.NewParseErr("", s.Pos, err)
		}
		s.Pos = 0
	}
	if s.Bytes()[s.Pos] == '}' {
		s.Pos++
		return result, nil
	}
	for {
		var key string
		key, err = s.KeyView(true)
		if err != nil {
			return result, decode.NewParseErr("", s.Pos, err)
		}
		switch key {
		case "id":
			err = s.ConsumeColon()
			if err != nil {
				return result, decode.NewParseErr("id", s.Pos, err)
			}
			if seenID {
				return result, &validation.DuplicateKeyError{Pos: s.Offset(), Path: []string{"id"}}
			}
			seenID = true
			var iv int64
			iv, err = s.Int64()
			if err != nil {
				return result, decode.NewParseErr("id", s.Pos, err)
			}
			result.ID = int(iv)
		case "slug":
			err = s.ConsumeColon()
			if err != nil {
				return result, decode.NewParseErr("slug", s.Pos, err)
			}
			if seenSlug {
				return result, &validation.DuplicateKeyError{Pos: s.Offset(), Path: []string{"slug"}}
			}
			seenSlug = true
			result.Slug, err = s.String(true)
			if err != nil {
				return result, decode.NewParseErr("slug", s.Pos, err)
			}
			if !isSlug(result.Slug) {
				return result, &validation.PredicateError{Pos: s.Offset(), Path: []string{"slug"}, Name: "isSlug", Msg: "", Value: result.Slug}
			}
		case "tags":
			err = s.ConsumeColon()
			if err != nil {
				return result, decode.NewParseErr("tags", s.Pos, err)
			}
			if seenTags {
				return result, &validation.DuplicateKeyError{Pos: s.Offset(), Path: []string{"tags"}}
			}
			seenTags = true
			err = s.SkipSpace()
			if err != nil {
				return result, decode.NewParseErr("tags", s.Pos, err)
			}
			if s.Pos >= len(s.Bytes()) {
				if err = s.ReadMore(0); err != nil {
					return result, decode.NewParseErr("tags", s.Pos, err)
				}
			}
			if s.Bytes()[s.Pos] == 'n' {
				for ki := 1; ki < 4; ki++ {
					if s.Pos+ki >= len(s.Bytes()) {
						if err = s.ReadMore(0); err != nil {
							return result, decode.NewParseErr("tags", s.Pos, err)
						}
					}
					if s.Bytes()[s.Pos+ki] != "null"[ki] {
						return result, decode.NewParseErr("tags", s.Pos, scan.ErrBadLiteral)
					}
				}
				s.Pos += 4
				result.Tags = nil
				break
			}
			err = s.ArrayOpen()
			if err != nil {
				return result, decode.NewParseErr("tags", s.Pos, err)
			}
			err = s.SkipSpace()
			if err != nil {
				return result, decode.NewParseErr("tags", s.Pos, err)
			}
			if s.Pos >= len(s.Bytes()) {
				if err = s.ReadMore(0); err != nil {
					return result, decode.NewParseErr("tags", s.Pos, err)
				}
			}
			if s.Bytes()[s.Pos] == ']' {
				if result.Tags == nil {
					result.Tags = []string{}
				}
			} else {
				if result.Tags == nil {
					result.Tags = make([]string, 0, 4)
				}
			}
			for s.Bytes()[s.Pos] != ']' {
				result.Tags = append(result.Tags, "")
				result.Tags[len(result.Tags)-1], err = s.String(true)
				if err != nil {
					return result, decode.NewParseErr("tags", s.Pos, err)
				}
				err = s.SkipSpace()
				if err != nil {
					return result, decode.NewParseErr("tags", s.Pos, err)
				}
				if s.Pos >= len(s.Bytes()) {
					if err = s.ReadMore(0); err != nil {
						return result, decode.NewParseErr("tags", s.Pos, err)
					}
				}
				if s.Bytes()[s.Pos] == ',' {
					s.Pos++
					err = s.SkipSpace()
					if err != nil {
						return result, decode.NewParseErr("tags", s.Pos, err)
					}
					if s.Pos >= len(s.Bytes()) || s.Bytes()[s.Pos] == ']' {
						return result, decode.NewParseErr("tags", s.Pos, scan.ErrBadArray)
					}
					continue
				}
				break
			}
			if s.Bytes()[s.Pos] != ']' {
				return result, decode.NewParseErr("tags", s.Pos, scan.ErrBadArray)
			}
			s.Pos++
		case "title":
			err = s.ConsumeColon()
			if err != nil {
				return result, decode.NewParseErr("title", s.Pos, err)
			}
			if seenTitle {
				return result, &validation.DuplicateKeyError{Pos: s.Offset(), Path: []string{"title"}}
			}
			seenTitle = true
			result.Title, err = s.String(true)
			if err != nil {
				return result, decode.NewParseErr("title", s.Pos, err)
			}
		default:
			return result, &validation.UnknownKeyError{Pos: s.Offset(), Path: []string{strings.Clone(key)}}
		}

		err = s.SkipSpace()
		if err != nil {
			return result, decode.NewParseErr("", s.Pos, err)
		}
		if s.Pos >= len(s.Bytes()) {
			if err = s.ReadMore(s.Pos); err != nil {
				return result, decode.NewParseErr("", s.Pos, err)
			}
			s.Pos = 0
		}
		c := s.Bytes()[s.Pos]
		if c == ',' {
			s.Pos++
			err = s.SkipSpace()
			if err != nil {
				return result, decode.NewParseErr("", s.Pos, err)
			}
			continue
		}
		if c == '}' {
			s.Pos++
			return result, nil
		}
		return result, decode.NewParseErr("", s.Pos, scan.ErrBadObject)
	}
}

func (s Post) JSONSize() int {
	size := 48
	size += len(s.Slug) * 2
	if len(s.Tags) > 0 {
		size += 12
		if n := len(s.Tags); n > 0 {
			size += n - 1
		}
		for i0 := range s.Tags {
			size += len(s.Tags[i0])*2 + 2
		}
	}
	size += len(s.Title) * 2
	return size
}

func (s Post) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, '{')
	start := len(dst)
	if len(dst) > start {
		dst = append(dst, ',')
	}
	dst = append(dst, "\"id\":"...)
	dst = strconv.AppendInt(dst, int64(s.ID), 10)
	if len(dst) > start {
		dst = append(dst, ',')
	}
	dst = append(dst, "\"slug\":\""...)
	dst = encode.AppendStringNoHTML(dst, s.Slug)
	if len(s.Tags) > 0 {
		if len(dst) > start {
			dst = append(dst, ',')
		}
		dst = append(dst, "\"tags\":"...)
		if s.Tags == nil {
			dst = append(dst, "null"...)
		} else {
			dst = append(dst, '[')
			if len(s.Tags) > 0 {
				dst = append(dst, '"')
				dst = encode.AppendStringNoHTML(dst, s.Tags[0])
				for _, v0 := range s.Tags[1:] {
					dst = append(dst, ",\""...)
					dst = encode.AppendStringNoHTML(dst, v0)
				}
			}
			dst = append(dst, ']')
		}
	}
	if len(dst) > start {
		dst = append(dst, ',')
	}
	dst = append(dst, "\"title\":\""...)
	dst = encode.AppendStringNoHTML(dst, s.Title)
	return append(dst, '}'), nil
}

func (recv User) DecodeFrom(data []byte) (result User, i int, err error) {
	result = recv
	seenName := false
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i >= len(data) || data[i] != '{' {
		return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
	}
	i++
	for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
		i++
	}
	if i < len(data) && data[i] == '}' {
		i++
		return result, i, nil
	}
	for {
		var key string
		if i >= len(data) || data[i] != '"' {
			return result, i, decode.NewParseErr("", i, scan.ErrExpectString)
		}
		ke := i + 1
		for ke < len(data) && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 && data[ke] < 0x80 {
			ke++
		}
		if ke >= len(data) {
			return result, i, decode.NewParseErr("", i, scan.ErrUnterminated)
		}
		if data[ke] < 0x20 {
			return result, i, decode.NewParseErr("", i, scan.ErrBadString)
		}
		if data[ke] == '"' {
			key = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
			i = ke + 1
		} else {
			key, i, err = scan.String(data, i, true)
			if err != nil {
				return result, i, decode.NewParseErr("", i, err)
			}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) || data[i] != ':' {
			return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
		}
		i++
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		switch key {
		case "name":
			if seenName {
				return result, i, &validation.DuplicateKeyError{Pos: i, Path: []string{"name"}}
			}
			seenName = true
			if i >= len(data) || data[i] != '"' {
				return result, i, decode.NewParseErr("name", i, scan.ErrExpectString)
			}
			ke := i + 1
			kew := ke + 32
			if kew > len(data) {
				kew = len(data)
			}
			for ke < kew && data[ke] != '"' && data[ke] != '\\' && data[ke] >= 0x20 && data[ke] < 0x80 {
				ke++
			}
			if ke < len(data) && data[ke] == '"' {
				result.Name = unsafe.String(unsafe.SliceData(data[i+1:]), ke-i-1)
				i = ke + 1
			} else {
				result.Name, i, err = scan.String(data, i, true)
				if err != nil {
					return result, i, decode.NewParseErr("name", i, err)
				}
			}
		default:
			return result, i, &validation.UnknownKeyError{Pos: i, Path: []string{key}}
		}
		for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
			i++
		}
		if i >= len(data) {
			return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
		}
		if data[i] == ',' {
			i++
			for i < len(data) && data[i] <= ' ' && (data[i] == ' ' || data[i] == '\t' || data[i] == '\n' || data[i] == '\r') {
				i++
			}
			continue
		}
		if data[i] == '}' {
			i++
			return result, i, nil
		}
		return result, i, decode.NewParseErr("", i, scan.ErrBadObject)
	}
}

func (recv User) DecodeFromStream(s *scan.Stream) (result User, err error) {
	result = recv
	seenName := false
	err = s.ObjectOpen()
	if err != nil {
		return result, decode.NewParseErr("", s.Pos, err)
	}
	err = s.SkipSpace()
	if err != nil {
		return result, decode.NewParseErr("", s.Pos, err)
	}
	if s.Pos >= len(s.Bytes()) {
		if err = s.ReadMore(s.Pos); err != nil {
			return result, decode.NewParseErr("", s.Pos, err)
		}
		s.Pos = 0
	}
	if s.Bytes()[s.Pos] == '}' {
		s.Pos++
		return result, nil
	}
	for {
		var key string
		key, err = s.KeyView(true)
		if err != nil {
			return result, decode.NewParseErr("", s.Pos, err)
		}
		switch key {
		case "name":
			err = s.ConsumeColon()
			if err != nil {
				return result, decode.NewParseErr("name", s.Pos, err)
			}
			if seenName {
				return result, &validation.DuplicateKeyError{Pos: s.Offset(), Path: []string{"name"}}
			}
			seenName = true
			result.Name, err = s.String(true)
			if err != nil {
				return result, decode.NewParseErr("name", s.Pos, err)
			}
		default:
			return result, &validation.UnknownKeyError{Pos: s.Offset(), Path: []string{strings.Clone(key)}}
		}

		err = s.SkipSpace()
		if err != nil {
			return result, decode.NewParseErr("", s.Pos, err)
		}
		if s.Pos >= len(s.Bytes()) {
			if err = s.ReadMore(s.Pos); err != nil {
				return result, decode.NewParseErr("", s.Pos, err)
			}
			s.Pos = 0
		}
		c := s.Bytes()[s.Pos]
		if c == ',' {
			s.Pos++
			err = s.SkipSpace()
			if err != nil {
				return result, decode.NewParseErr("", s.Pos, err)
			}
			continue
		}
		if c == '}' {
			s.Pos++
			return result, nil
		}
		return result, decode.NewParseErr("", s.Pos, scan.ErrBadObject)
	}
}

func (s User) JSONSize() int {
	size := 11
	size += len(s.Name) * 2
	return size
}

func (s User) AppendJSON(dst []byte) ([]byte, error) {
	var err error
	_ = err
	dst = append(dst, "{\"name\":\""...)
	dst = encode.AppendStringNoHTML(dst, s.Name)
	return append(dst, '}'), nil
}
